#SENSU_NAMESPACE: my_namespace
#SENSU_SUBSCRIPTION: sub_name
#SENSU_BACKEND: be_url.tls
#SENSU_BACKEND_IP: xx.xx.xx.xx
#PORT: xxxx
---
SENSU_NAMESPACE: eehcvms
SENSU_SUBSCRIPTION: system
SENSU_BACKEND: sensu02.fixed.ninja
SENSU_BACKEND_IP: 41.128.178.133
PORT: 5666


