---
  - name: "Creating Senus Home Directory"
    file:
      path: /home/sensu
      state: directory
      mode: '0755'

  - name: "Changing Sesnu User shell and Home Directory"
    user:
      name: sensu
      shell: /bin/bash
      groups: sensu
      home: /home/sensu

  - name: "Copying bash* Files - Redhat & CentOS"
    shell: cp /root/{{ item }} /home/sensu/
    with_items:
      - .bashrc
      - .bash_profile
      - .bash_history
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'CloudLinux'

  - name: "Copying bash* Files - Debian & Ubuntu"
    shell: cp /root/{{ item }} /home/sensu/
    with_items:
      - .bashrc     
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: "Changing Sensu Home Directory Ownership"
    file:
      path: /home/sensu
      state: directory
      recurse: yes
      owner: sensu

#  - name: "Add User To SUDO Without Password"
#    lineinfile:
#      path: /etc/sudoers
#      regexp: '^%wheel'
#      insertbefore: '^# %wheel'
#      line: '%sensu ALL=(ALL) NOPASSWD: ALL'
#      validate: 'visudo -cf %s'
#    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'CloudLinux'

  - import_tasks: setup/rhel_family/rhel_prep_for_ruby.yml
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'CloudLinux'

  - import_tasks: setup/debian_family/debian_prep_for_ruby.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'



